### ISSUE TITLE
Need an applied action metric and meta object return containing verbose info .

### ISSUE THREAD

**Issue by samarth** [paytm/youknowwho#8]
At times if the rule engine is abused, the chances are that majority of the rules would become true .

This would mean the most of the actions are being applied which would eventually lead in the latency of the application ...

Need some way we can monitor the applied action percentage of the rule engine on a daily / weekly basis.

**Comment by shreyagarwal** [comment]
E.g 50 rules are there. And for each iteration all 50 are getting executed. Then we should be able to collect stats such as for a single iteration , how many were positive , how many negataive... Hoe many total negative conditions ... Average negative conditions per negative rule ... This will help us reduce conditions and rearrange conditions in a rule...
